---
- hosts: all
  remote_user: "{{ ubuntu_common_deploy_user_name }}"
  become: yes
  become_method: sudo

  roles:
    - common
    - mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.apache-php-fpm
    - geerlingguy.php-mysql
    - websites
    - certbot
