---
UBUNTU_COMMON_ROOT_PASSWORD: "{{ vault_UBUNTU_COMMON_ROOT_PASSWORD }}"
UBUNTU_COMMON_DEPLOY_PASSWORD: "{{ vault_UBUNTU_COMMON_DEPLOY_PASSWORD }}"
UBUNTU_COMMON_LOGWATCH_EMAIL: "{{ vault_UBUNTU_COMMON_LOGWATCH_EMAIL }}"
ubuntu_common_deploy_user_name: "{{ vault_ubuntu_common_deploy_user_name }}"
ubuntu_common_deploy_public_keys:
  - ~/.ssh/id_rsa.pub
server_admin_email: "{{ vault_server_admin_email }}"

mysql_root_password_plain: "{{ vault_mysql_root_password_plain }}"
mysql_deploy_user_name: "{{ vault_mysql_deploy_user_name }}"
mysql_deploy_user_password_plain: "{{ vault_mysql_deploy_user_password_plain }}"

ubuntu_common_ssh_port: "{{ vault_ubuntu_common_ssh_port }}"
ansible_port: "{{ vault_ubuntu_common_ssh_port }}"

ansible_become_pass: "{{ vault_UBUNTU_COMMON_DEPLOY_PASSWORD_PLAIN }}"

ubuntu_common_required_packages:
  - ufw
  - fail2ban
  - unattended-upgrades
  - logwatch
  - build-essential

fail2ban:
  config:
    ignoreip: 127.0.0.1/8
    bantime: 3600
    maxretry: 3

web_domains: "{{ vault_web_domains }}"
